### ISSUE TITLE
Bugfixes & extensions for flare

### ISSUE THREAD

**Issue by cboettig** [eco4cast/score4cast#3]
- [x] Does it require the targets and forecasts to all have site_id, x, y, z columns?

- [x] Can we have the script not parse the file name for column values like model_id, etc if those columns are provided in the forecast file. 

- [x] The horizon calculation does not allow for negative horizons.  If start_time is provided as a column then it can easily substract time - start_time to get horizon.  If start_time is not provided then it is ok to assume the start_time is the min(time)

from @rqthomas .

**Comment by cboettig** [comment]
ok fixed requirement for x,y,z in https://github.com/eco4cast/score4cast/commit/ddd1296478cb18c21f5acd9ae4caea3363850bb6 . 1/3

**Comment by cboettig** [comment]
For the horizon, the current code to compute the horizon is:


https://github.com/eco4cast/score4cast/blob/ddd1296478cb18c21f5acd9ae4caea3363850bb6/R/include_horizon.R#L10-L22

So as you can see, it assumes basically that we only have `time` as given, and that `start_time = min(time)` and horizon is thus `time - start_time` , i.e. `time - min(time)`.  

If the user has already supplied a `start_time` (or an `interval` column), it will attempt to `left_join` on that column as well (which will obviously lead to miss-matches if the declared `start_time` isn't `time - min(time)`.  https://github.com/eco4cast/score4cast/blob/ddd1296478cb18c21f5acd9ae4caea3363850bb6/R/include_horizon.R#L19 .  

I guess we should: 

-  have it use only the user-provided start_time from `df` instead of computing the interval when available.  
- not calculate either `horizon` or `interval` if provided

maybe we should not have `interval` column in the final output?  (I think it's non-standard?  we were calculating it because we had been doing `start_time = min(time) - interval[1]` but looks like we changed that. )

**Comment by cboettig** [comment]
@rqthomas `include_horizon()` method will now compute horizon and start_time only when not provided; using the definitions: `start_time` = `min(time)` and `horizon = time - start_time` (note that fn respects grouping over target id model id etc.  Haven't tested thoroughly yet.

Also dropped `interval` from the columns in the output score, but happy to be convinced to keep it.  

Still need to think through the filename parsing. What exactly should be the rule here.  Currently we do:

https://github.com/eco4cast/score4cast/blob/ddd1296478cb18c21f5acd9ae4caea3363850bb6/R/standardize_format.R#L89-L92

as part of standardize_format() on any forecast file.  What should the correct behavior be here?  do we want to scrap this entirely and insist these values be specified in a column of the forecast (or given as an optional argument somewhere?)  If we keep some form of name parsing, what rule(s) do we use to decide when it is safe to parse a name as `<target_id>-<start_time>-<model_id>` and when should it b parsed according to some other conventions?  Or do we make the filename convention an argument to the functions?

**Comment by rqthomas** [comment]
I think we should work towards not parsing the filename at all and insist these values are in a column.  We will need to update the forecasting challenge documentation to reflect this and make it backwards compatible using file name parsing as we transition

**Comment by cboettig** [comment]
@rqthomas nice, I like it.  I'll have it check for column names first then, and parse based on the old convention only if the columns are missing.
